<?php

namespace App\Http\Controllers;

use App\Services\GatewayConfigRepository;
use App\Services\Payments\MpesaService;
use App\Models\Payment;
use App\Models\Transaction;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use App\Models\ClientApp;

class MakePaymentController extends Controller
{
    public function __construct(private readonly GatewayConfigRepository $gatewayConfig)
    {
    }

    public function initiate(Request $request)
    {
        $validated = $request->validate([
            'payment_method' => 'required|string',
            'payer_phone' => 'required_without:phone|string',
            'phone' => 'nullable|string', // legacy support
            'amount' => 'required|numeric',
            // reference will be autogenerated; if provided, still enforce uniqueness
            'reference' => 'nullable|string|unique:payments,reference',
            'student_full_name' => 'required|string',
            'student_email' => 'nullable|email',
            'course_name' => 'nullable|string',
            'payer_name' => 'nullable|string',
            'client_app_id' => 'nullable|exists:client_apps,id',
        ]);

        // Backward compatibility: if legacy 'phone' was sent, map it to payer_phone
        if (($validated['payer_phone'] ?? null) === null && !empty($validated['phone'] ?? null)) {
            $validated['payer_phone'] = $validated['phone'];
        }

        $method = $validated['payment_method'];
        $service = $this->getPaymentService($method);

        // Autogenerate reference if not supplied
        if (empty($validated['reference'])) {
            $validated['reference'] = $this->generateReference($method);
        }

        // 1️⃣ Create payment record
        $payment = Payment::create([
            'client_app_id' => $validated['client_app_id'] ?? null,
            'reference' => $validated['reference'],
            'student_full_name' => $validated['student_full_name'],
            'student_email' => $validated['student_email'] ?? null,
            'payer_name' => $validated['payer_name'] ?? $validated['student_full_name'],
            'payer_phone' => $validated['payer_phone'] ?? $validated['phone'],
            'course_name' => $validated['course_name'] ?? null,
            'amount' => $validated['amount'],
            'status' => 'pending',
            'payment_method' => $method,
        ]);

        // 2️⃣ Initiate transaction
        $result = $service->initiate($validated);

        // 3️⃣ Log transaction
        Transaction::create([
            'payment_id' => $payment->id,
            'checkout_request_id' => $result['CheckoutRequestID'] ?? null,
            'merchant_request_id' => $result['MerchantRequestID'] ?? null,
            'amount' => $validated['amount'],
            'phone' => $validated['payer_phone'],
            'status' => 'initiated',
            'raw_response' => $result,
        ]);

        // 4️⃣ Do not clear session prefill here; we need return_url/user context for completion

        return response()->json([
            'message' => 'Payment initiated',
            'payment_id' => $payment->id,
            'response' => $result,
        ]);
    }

    public function status(Request $request, Payment $payment)
    {
        $prefill = $request->session()->get('pay.prefill', []);
        return response()->json([
            'status' => $payment->status,
            'payment_id' => $payment->id,
            'return_url' => $prefill['return_url'] ?? null,
        ]);
    }

    public function complete(Request $request, Payment $payment)
    {
        if (strtolower($payment->status) !== 'success') {
            return redirect()->route('pay.index')->with('status', 'Payment not completed yet.');
        }

        $prefill = $request->session()->get('pay.prefill', []);

        $client = $payment->clientApp;
        $callbackUrl = $client?->callback_url;

        $payload = [
            'reference' => (string)$payment->reference,
            'status' => (string)$payment->status,
            'amount' => (float)$payment->amount,
            'client_app_id' => $client?->id ? (string)$client->id : null,
            'course_id' => $prefill['course_id'] ?? null,
            'user_id' => $prefill['user_id'] ?? null,
            'ts' => time(),
        ];

        // Sign payload if api_secret is available
        $signature = null;
        if (!empty($client?->api_secret)) {
            $verify = $payload;
            ksort($verify);
            $base = http_build_query($verify, '', '&', PHP_QUERY_RFC3986);
            $signature = hash_hmac('sha256', $base, $client->api_secret);
            $payload['signature'] = $signature;
        }

        // Post to client callback if configured
        if (!empty($callbackUrl)) {
            try {
                $resp = Http::asForm()->post($callbackUrl, $payload);
                Log::info('Posted payment completion to client callback', [
                    'url' => $callbackUrl,
                    'status' => $resp->status(),
                ]);
            } catch (\Throwable $e) {
                Log::error('Failed posting to client callback', [
                    'url' => $callbackUrl,
                    'error' => $e->getMessage(),
                ]);
            }
        }

        // Redirect user to return_url if present
        $returnUrl = $prefill['return_url'] ?? null;

        // Clear session prefill now that flow is complete
        try {
            $request->session()->forget('pay.prefill');
        } catch (\Throwable $e) {
            // ignore
        }

        if (!empty($returnUrl)) {
            return redirect()->away($returnUrl);
        }

        return redirect()->route('pay.index')->with('status', 'Payment complete');
    }

    private function getPaymentService($method)
    {
        return match ($method) {
            'mpesa' => new MpesaService($this->gatewayConfig),
            // 'airtel' => new AirtelService(),
            // 'card' => new CardService(),
            // 'ecitizen' => new EcitizenService(),
            default => throw new \Exception('Unsupported payment method')
        };
    }

    private function generateReference(string $method): string
    {
        $prefix = match (strtolower($method)) {
            'mpesa' => 'MPE',
            'airtel' => 'ARM',
            'card' => 'CRD',
            'ecitizen' => 'ECZ',
            default => 'PAY',
        };

        // Try a few times to avoid collision with DB unique constraint
        for ($i = 0; $i < 5; $i++) {
            // Example: 20251013 074530123 becomes 20251013074530123 (YmdHisv)
            $timeMs = Carbon::now()->format('YmdHisv');
            $suffix = $timeMs . '-' . Str::upper(Str::random(4));
            $ref = $prefix . '-' . $suffix;
            if (!Payment::where('reference', $ref)->exists()) {
                return $ref;
            }
            usleep(1000); // wait 1ms before retry to avoid duplicate ms timestamp
        }

        // Final fallback with longer random segment
        $timeMs = Carbon::now()->format('YmdHisv');
        return $prefix . '-' . $timeMs . '-' . Str::upper(Str::random(8));
    }
}
