<?php

namespace App\Http\Controllers;

use App\Services\Payments\MpesaService;
use App\Models\Payment;
use App\Models\Transaction;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Carbon\Carbon;

class MakePaymentController extends Controller
{
    public function initiate(Request $request)
    {
        $validated = $request->validate([
            'payment_method' => 'required|string',
            'phone' => 'required|string',
            'amount' => 'required|numeric',
            // reference will be autogenerated; if provided, still enforce uniqueness
            'reference' => 'nullable|string|unique:payments,reference',
            'student_full_name' => 'required|string',
            'student_email' => 'nullable|email',
            'student_phone' => 'nullable|string',
            'payer_name' => 'nullable|string',
            'payer_phone' => 'nullable|string',
            'course_name' => 'nullable|string',
            'client_app_id' => 'nullable|exists:client_apps,id',
        ]);

        $method = $validated['payment_method'];
        $service = $this->getPaymentService($method);

        // Autogenerate reference if not supplied
        if (empty($validated['reference'])) {
            $validated['reference'] = $this->generateReference($method);
        }

        // 1️⃣ Create payment record
        $payment = Payment::create([
            'client_app_id' => $validated['client_app_id'] ?? null,
            'reference' => $validated['reference'],
            'student_full_name' => $validated['student_full_name'],
            'student_email' => $validated['student_email'] ?? null,
            'student_phone' => $validated['student_phone'] ?? $validated['phone'],
            'payer_name' => $validated['payer_name'] ?? $validated['student_full_name'],
            'payer_phone' => $validated['payer_phone'] ?? $validated['phone'],
            'course_name' => $validated['course_name'] ?? null,
            'amount' => $validated['amount'],
            'status' => 'pending',
            'payment_method' => $method,
        ]);

        // 2️⃣ Initiate transaction
        $result = $service->initiate($validated);

        // 3️⃣ Log transaction
        Transaction::create([
            'payment_id' => $payment->id,
            'checkout_request_id' => $result['CheckoutRequestID'] ?? null,
            'merchant_request_id' => $result['MerchantRequestID'] ?? null,
            'amount' => $validated['amount'],
            'phone' => $validated['phone'],
            'status' => 'initiated',
            'raw_response' => $result,
        ]);

        return response()->json([
            'message' => 'Payment initiated',
            'payment_id' => $payment->id,
            'response' => $result,
        ]);
    }
    
    private function getPaymentService($method)
    {
        return match ($method) {
            'mpesa' => new MpesaService(),
            // 'airtel' => new AirtelService(),
            // 'card' => new CardService(),
            // 'ecitizen' => new EcitizenService(),
            default => throw new \Exception('Unsupported payment method')
        };
    }

    private function generateReference(string $method): string
    {
        $prefix = match (strtolower($method)) {
            'mpesa' => 'MPE',
            'airtel' => 'ARM',
            'card' => 'CRD',
            'ecitizen' => 'ECZ',
            default => 'PAY',
        };

        // Try a few times to avoid collision with DB unique constraint
        for ($i = 0; $i < 5; $i++) {
            // Example: 20251013 074530123 becomes 20251013074530123 (YmdHisv)
            $timeMs = Carbon::now()->format('YmdHisv');
            $suffix = $timeMs . '-' . Str::upper(Str::random(4));
            $ref = $prefix . '-' . $suffix;
            if (!Payment::where('reference', $ref)->exists()) {
                return $ref;
            }
            usleep(1000); // wait 1ms before retry to avoid duplicate ms timestamp
        }

        // Final fallback with longer random segment
        $timeMs = Carbon::now()->format('YmdHisv');
        return $prefix . '-' . $timeMs . '-' . Str::upper(Str::random(8));
    }
}
